export const SIMILAR_RESULTS_GET = "SIMILAR_RESULTS_GET";
export const SIMILAR_RESULTS_GET_SUCCESS = "SIMILAR_RESULTS_GET_SUCCESS";
export const SIMILAR_RESULTS_GET_FAIL = "SIMILAR_RESULTS_GET_FAIL";
export const SIMILAR_RESULTS_CLEAR = "SIMILAR_RESULTS_CLEAR";
