export const SPECIFIC_MOVIE_GET = "SPECIFIC_MOVIE_GET";
export const SPECIFIC_MOVIE_GET_SUCCESS = "SPECIFIC_MOVIE_GET_SUCCESS";
export const SPECIFIC_MOVIE_GET_FAIL = "SPECIFIC_MOVIE_GET_FAIL";
export const SPECIFIC_MOVIE_CLEAR = "SPECIFIC_MOVIE_CLEAR";

export const RELATED_MOVIES_GET = "RELATED_MOVIES_GET";
export const RELATED_MOVIES_GET_SUCCESS = "RELATED_MOVIES_GET_SUCCESS";
export const RELATED_MOVIES_GET_FAIL = "RELATED_MOVIES_GET_FAIL";
export const RELATED_MOVIES_CLEAR = "RELATED_MOVIES_CLEAR";
