export const SPECIFIC_MOVIE_GET = 'SPECIFIC_MOVIE_GET';
export const SPECIFIC_MOVIE_GET_SUCCESS = 'SPECIFIC_MOVIE_GET_SUCCESS';
export const SPECIFIC_MOVIE_GET_FAIL = 'SPECIFIC_MOVIE_GET_FAIL';
export const SPECIFIC_MOVIE_CLEAR = 'SPECIFIC_MOVIE_CLEAR';
