export const SPECIFIC_MOVIE_GET = 'SPECIFIC_MOVIE_GET';
export const SPECIFIC_MOVIE_GET_SUCCESS = 'SPECIFIC_MOVIE_GET_SUCCESS';
export const SPECIFIC_MOVIE_GET_FAIL = 'SPECIFIC_MOVIE_GET_FAIL';
export const SPECIFIC_MOVIE_CLEAR = 'SPECIFIC_MOVIE_CLEAR';

export const SIMILAR_RESULTS_GET = "SIMILAR_RESULTS_GET";
export const SIMILAR_RESULTS_GET_SUCCESS = "SIMILAR_RESULTS_GET_SUCCESS";
export const SIMILAR_RESULTS_GET_FAIL = "SIMILAR_RESULTS_GET_FAIL";
export const SIMILAR_RESULTS_CLEAR = "SIMILAR_RESULTS_CLEAR";
